apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  ports:
    - port: 80
    #targetPort: 80 é assumindo quando não declaramos
      nodePort: 30000
  selector:
    app: primeiro-pod